#!/bin/bash

cd
rm -rf AUTORUN-CCMINER-GITHUB
git clone https://github.com/Mr-Kamol/AUTORUN-CCMINER-X
cd ../etc/mobile-mining/set-miner
cp -r online.json offline.json /../root/AUTORUN-CCMINER-X/mobile-mining/set-miner
cd
cd ../etc
rm -rf mobile-mining
cd
cd ../bin
rm -rf add-ip edit-miner run-miner update down-grade
cd
cd AUTORUN-CCMINER-X
chmod +x setupdate.sh
sh setupdate.sh
